// <auto-generated />
using AggregationApp.Data.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AggregationApp.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230303111345_addedDatamodelstodatabase")]
    partial class addedDatamodelstodatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AggregationApp.Data.Models.ElectricInsertDataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Tinklas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TotalPMinus")
                        .HasColumnType("float");

                    b.Property<double>("TotalPPlus")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("ElectricityModels");
                });
#pragma warning restore 612, 618
        }
    }
}
