// <auto-generated />
using AggregationApp.Data.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AggregationApp.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AggregationApp.Data.Models.ElectricCityModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Obj_Gv_Tipas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Obj_Numeris")
                        .HasColumnType("int");

                    b.Property<string>("Obt_Pavadinimas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("P_Minus")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("P_Plus")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Pl_T")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tinklas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPMinus")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPPlus")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ElectricityModels");
                });
#pragma warning restore 612, 618
        }
    }
}
